InventoryTracker-WebApp/Controllers/EntityController.cs
using DocumentFormat.OpenXml.Spreadsheet;
using InventoryTracker_WebApp.Domain.Entity;
using InventoryTracker_WebApp.Domain.Equipment;
using InventoryTracker_WebApp.Helpers;
using InventoryTracker_WebApp.Models;
using Newtonsoft.Json;
using SpreadsheetLight;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventoryTracker_WebApp.Controllers
{
    [SessionTimeout]
    public class EntityController : Controller
    {
        private readonly IEntityRepository _entityRepository;
        private readonly IEquipmentRepository _equipmentRepository;

        public EntityController(IEntityRepository entityRepository, IEquipmentRepository equipmentRepository)
        {
            this._entityRepository = entityRepository;
            this._equipmentRepository = equipmentRepository;
        }

        #region Entity Template
        public ActionResult Index()
        {
            return View();
        }

        public string GetEntityTemplate(string entityType)
        {
            List<EntityTemplate> entityTemplates = _entityRepository.GetEntityTemplates(entityType);

            var uniqueEntityTemplates = entityTemplates.GroupBy(x => new
            {
                x.Ent_type
            }).Select(x => new EntityTemplate
            {
                Ent_type = x.Key.Ent_type
            }).ToList();

            var uniquePropName = entityTemplates.GroupBy(x => new
            {
                x.Prop_name
            }).Select(x => new EntityTemplate
            {
                Prop_name = x.Key.Prop_name
            }).ToList();

            var uniquePropNameEnt = entityTemplates.GroupBy(x => new
            {
                x.Ent_type,
                x.Prop_name
            }).Select(x => new EntityTemplate
            {
                Ent_type = x.Key.Ent_type,
                Prop_name = x.Key.Prop_name
            }).ToList();

            return JsonConvert.SerializeObject(new { IsValid = true, data = entityTemplates, uniqueEntityTemplates = uniqueEntityTemplates, uniquePropName = uniquePropName, uniquePropNameEnt = uniquePropNameEnt });
        }
        public string GetEntityHeaders(string searchString)
        {
            List<EntityHeader> entityHeaders = _entityRepository.GetEntityHeaders(searchString);
            int totalCount = _entityRepository.GetEntityHeaderRowCount();
            return JsonConvert.SerializeObject(new { IsValid = true, data = entityHeaders, totalCount = totalCount });
        }
        public string GetEntityHeaderfromEntityEquipment(string searchString, string startDate)
        {
            List<EntityHeader> entityHeaders = _entityRepository.GetEntityHeaderfromEntityEquipment(searchString, startDate);
            int totalCount = _entityRepository.GetEntityHeaderRowCount();
            return JsonConvert.SerializeObject(new { IsValid = true, data = entityHeaders, totalCount = totalCount });
        }

        [HttpPost]
        public string SaveEntityTemplate(string entityTemplate)
        {
            List<EntityTemplate> entityTemplates = JsonConvert.DeserializeObject<List<EntityTemplate>>(entityTemplate);
            if (entityTemplates.Count > 0 && entityTemplates.Find(x => x.Prop_name.ToLower() == "latitude") != null && entityTemplates.Find(x => x.Prop_name.ToLower() == "longitude") != null)
            {
                bool isSaved = _entityRepository.SaveEntityTemplate(entityTemplates);
                return JsonConvert.SerializeObject(new { IsValid = true, data = isSaved });
            }
            return JsonConvert.SerializeObject(new { IsValid = false, data = false });
        }

        [HttpPost]
        public string DeleteEntity(string entityType)
        {
            if (!string.IsNullOrEmpty(entityType))
            {
                bool isDeleted = _entityRepository.DeleteEntityTemplates(entityType);
                return JsonConvert.SerializeObject(new { IsValid = true, data = isDeleted });
            }
            return JsonConvert.SerializeObject(new { IsValid = false, data = false });
        }

        [HttpGet]
        public string GetEntityTemplateDetails(int entityID, string startDate)
        {
            if (entityID > 0)
            {
                List<EntityDetail> entityTempDetails = _entityRepository.GetEntityTemplateDetails(entityID, startDate);
                List<EntityDetail> AllEntityTemplateProp = _entityRepository.GetAllEntityTemplateProp(entityID);

                List<EquipmentHeader> equipmentHeaders = _entityRepository.GetEntityEquipmentAssignment(entityID);
                return JsonConvert.SerializeObject(new { IsValid = true, data = entityTempDetails, equipmentHeaders = equipmentHeaders, defaultentity = AllEntityTemplateProp });
            }
            return JsonConvert.SerializeObject(new { IsValid = false, data = false });
        }

        [HttpGet]
        public string GetAllEntityTemplateDetails()
        {
            List<EntityDetail> entTempDetails = _entityRepository.GetAllEntityTemplateDetails();
            return JsonConvert.SerializeObject(new { IsValid = true, data = entTempDetails });
        }

        [HttpPost]
        public string RemoveEntityEquipmentTemplateDetail(int deatailID, int isEntity)
        {
            try
            {
                if (deatailID > 0)
                {
                    var isDeleted = _entityRepository.RemoveEntityEquipmentTemplateDetail(deatailID, isEntity);
                    if (isDeleted)
                    {
                        return JsonConvert.SerializeObject(new { IsValid = true, data = "Data deleted successfully!" });
                    }
                }
                return JsonConvert.SerializeObject(new { IsValid = false, data = "Data not deleted!" });
            }
            catch (Exception e)
            {
                return JsonConvert.SerializeObject(new { IsValid = false, data = "Data not deleted!" });
            }
        }
        #endregion

        #region Entity Search

        public ActionResult EntitySearch()
        {
            return View();
        }
        [HttpGet]
        public string EntityValueByPropName(string propName, string date)
        {
            if (!string.IsNullOrEmpty(propName))
            {
                List<EntityDetail> entityDetails = _entityRepository.EntityValueByPropName(propName, date);
                return JsonConvert.SerializeObject(new { IsValid = true, data = entityDetails });
            }
            return JsonConvert.SerializeObject(new { IsValid = false, data = false });
        }

        [HttpPost]
        public string DeleteEntityHeader(int entityID)
        {
            if (entityID > 0)
            {
                bool isDeleted = _entityRepository.DeleteEntityHeader(entityID);
                return JsonConvert.SerializeObject(new { IsValid = true, data = isDeleted });
            }
            return JsonConvert.SerializeObject(new { IsValid = false, data = false });
        }

        [HttpPost]
        public string SaveEntityHDRTempData(string entityHDR, string entityTmpDtl, string currEntDTLID)
        {
            if (!string.IsNullOrEmpty(entityHDR))
            {
                List<EntityHeader> entityHeaders = JsonConvert.DeserializeObject<List<EntityHeader>>(entityHDR);
                List<EntityDetail> entityDtl = JsonConvert.DeserializeObject<List<EntityDetail>>(entityTmpDtl);
                if (entityHeaders[0].ENT_ID == 0)
                {
                    bool isDuplicate = _entityRepository.CheckDuplicateEntityHDR(entityHeaders[0]);
                    if (isDuplicate)
                    {
                        return JsonConvert.SerializeObject(new { IsValid = false, data = "This entity header is already exist." });
                    }
                }
                bool isInserted = _entityRepository.SaveEntityHDR(entityHeaders[0], entityDtl, currEntDTLID);
                if (!isInserted)
                {
                    return JsonConvert.SerializeObject(new { IsValid = true, data = "Value is already present on selected date range for this property." });
                }
                return JsonConvert.SerializeObject(new { IsValid = true, data = "Data save successfully!" });
            }
            return JsonConvert.SerializeObject(new { IsValid = false });
        }

        #endregion

        #region  Entity Equipment Assignment
        public ActionResult EntityEquipmentAssignment()
        {
            return View();
        }
        #endregion

        #region Entity Export - Import

        public FileResult Export(string startDate, string searchString)
        {
            try
            {
                var entity = _entityRepository.ExportEntity(startDate, searchString);

                int newcolumnCount = 0;
                var firstEntityIDCount = entity[0].Columns.Count;
                var valueStr = "Value";
                var startDateStr = "Start Date";
                var endDateStr = "End Date";
                var entDtlIDStr = "Ent_Dtl_ID";
                foreach (var eRows in entity[0].Rows.Cast<DataRow>())
                {
                    var j = firstEntityIDCount;
                    var rowList = entity[1].Rows.Cast<DataRow>().Where(x => x.ItemArray[1].Equals(eRows[1]) && x.ItemArray[0].Equals(eRows[0])).OrderBy(x => x.ItemArray[4]).ToList();
                    foreach (var eRowsVal in rowList)
                    {
                        if (newcolumnCount < rowList.Count)
                        {
                            entity[0].Columns.Add(entDtlIDStr);
                            entity[0].Columns.Add(valueStr);
                            entity[0].Columns.Add(startDateStr);
                            entity[0].Columns.Add(endDateStr);
                            newcolumnCount++;

InventoryTracker-WebApp/Controllers/MapController.cs
using InventoryTracker_WebApp.Domain.Entity;
using InventoryTracker_WebApp.Domain.Equipment;
using InventoryTracker_WebApp.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace InventoryTracker_WebApp.Controllers
{
    public class MapController : Controller
    {

        private readonly IEntityRepository _entityRepository;
        private readonly IEquipmentRepository _equipmentRepository;

        public MapController(IEntityRepository entityRepository,IEquipmentRepository equipmentRepository)
        {
            this._entityRepository = entityRepository;
            this._equipmentRepository = equipmentRepository;
        }
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public string GetEntityLatLong()
        {
            List<EntityDetail> entityLatLong = _entityRepository.GetEntityTemplateDetails(0, string.Empty).Where(x => x.Prop_Name.Trim().ToLower() == "latitude" || x.Prop_Name.Trim().ToLower() == "longitude").OrderBy(x => x.Start_Date).OrderBy(x => x.End_Date).OrderBy(x => x.Ent_ID).ToList();
            return JsonConvert.SerializeObject(new { IsValid = true, entityLatLong = entityLatLong });
        }

        public string GetEntityEquipmentData()
        {
            var entityNumericPropValue = _entityRepository.GetEntityNumericProp();
            var entityNumericProp = entityNumericPropValue.Select(x => new EntityTemplate
            {
                Ent_type = x.Ent_type,
                Prop_name = x.Prop_name
            }).GroupBy(x => new
            {
                x.Ent_type,
                x.Prop_name
            }).Select(x => new EntityTemplate
            {
                Ent_type = x.Key.Ent_type,
                Prop_name = x.Key.Prop_name
            }).ToList();

            var equipNumericPropValue = _equipmentRepository.GetEquipmentNumericProp();

            var equipTempList = _equipmentRepository.GetEquipmentTemplatesForMap();
            var equipNumericProp = equipTempList.Select(x => new EquipmentTemplate
            {
                Equipment_Type = x.Equipment_Type,
                Prop_Name = x.Prop_Name 
            }).GroupBy(x => new
            {
                x.Equipment_Type,
                x.Prop_Name
            }).Select(x => new EquipmentTemplate
            {
                Equipment_Type = x.Key.Equipment_Type,
                Prop_Name = x.Key.Prop_Name
            }).ToList();

            var equipNullNumericProp = _equipmentRepository.GetEquipmentNullNumericProp();

            var getAllEnEqAss = _entityRepository.GetAllEntityEquipmentAssignment();
            var uniqueEnEqAss = getAllEnEqAss.Select(x => new MapDetail
            {
                ENT_TYPE = x.ENT_TYPE,
                EQUIP_TYPE = x.EQUIP_TYPE
            }).GroupBy(x => new
            {
                x.ENT_TYPE,
                x.EQUIP_TYPE
            }).Select(x => new MapDetail
            {
                ENT_TYPE = x.Key.ENT_TYPE,
                EQUIP_TYPE = x.Key.EQUIP_TYPE
            }).ToList();

            return JsonConvert.SerializeObject(new { IsValid = true, entityNumericProp = entityNumericProp, entityNumericPropValue = entityNumericPropValue, equipNumericPropValue= equipNumericPropValue, equipNumericProp= equipNumericProp, getAllEnEqAss= getAllEnEqAss, uniqueEnEqAss = uniqueEnEqAss, equipNullNumericProp = equipNullNumericProp });

        }
    }
}

InventoryTracker-WebApp/Controllers/UserMasterController.cs
using InventoryTracker_WebApp.Domain.Admin;
using InventoryTracker_WebApp.Domain.UserMaster;
using InventoryTracker_WebApp.Helpers;
using Newtonsoft.Json;
using System;
using System.Web.Mvc;

namespace InventoryTracker_WebApp.Controllers
{
    [SessionTimeout]
    public class UserMasterController : Controller
    {
        private IUserMasterRepository _userMasterRepository;
        private IAdminRepository _adminRepository;
        public UserMasterController(IUserMasterRepository userMasterRepository, IAdminRepository adminRepository)
        {
            _userMasterRepository = userMasterRepository;
            _adminRepository = adminRepository;
        }
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public string DeleteUser(int id)
        {
            try
            {
                var result = _userMasterRepository.DeleteUser(id);
                return JsonConvert.SerializeObject(new { IsValid = result, Data = "" });
            }
            catch (Exception ex)
            {
                return JsonConvert.SerializeObject(new { IsValid = false, data = ex.Message });
            }
        }

        [HttpPost]
        public string AddNewUser(string userName)
        {
            var result2 = "";
            try
            {
                var result = _userMasterRepository.AddNewUser(userName);

                if (result.Status)
                {
                    result2 = "User has been Created Successfully. ";
                    try
                    {
                        if (result.Data)
                        {
                            Helper.SendEmail(userName, result.Message, true,_adminRepository);
                        }

                    }
                    catch (Exception ex)
                    {
                        return JsonConvert.SerializeObject(new { IsValid = result.Status, Data = "", Message = result2 + "Email Not Sent." }); ;
                    }
                }
                else
                {
                    result2 = "User has not been created.";
                }
                return JsonConvert.SerializeObject(new { IsValid = result.Status, Data = "", Message = result2 });
            }
            catch (Exception ex)
            {
                result2 = "Something went wrong.PLease try again after some time.";
                return JsonConvert.SerializeObject(new { IsValid = false, data = ex.Message, Message = result2 });
            }
        }

        [HttpGet]
        public string GetAllUsers()
        {
            try
            {
                var allUsers = _userMasterRepository.GetAllUsers();
                return JsonConvert.SerializeObject(new
                {
                    IsValid = true,
                    allUsers = allUsers
                });
            }
            catch (Exception ex)
            {
                return JsonConvert.SerializeObject(new { IsValid = false, data = ex.Message });
            }
        }

        public string ResetPassword(string UserEmail)
        {
            try
            {
                var result = _userMasterRepository.ResetPassword(UserEmail);
                if (result.Status)
                {
                    Helper.SendEmail(UserEmail, result.Message, false,_adminRepository);
                }
                return JsonConvert.SerializeObject(new { IsValid = result.Status, Data = "", Message = "Password Reset Successful." });
            }
            catch (Exception ex)
            {
                return JsonConvert.SerializeObject(new { IsValid = false, data = ex.Message, Message = "Something went wrong. Please try again after some time." });
            }
        }
    }
}

InventoryTracker-WebApp/Views/Shared/_AssignmentButtons.cshtml
<div class="mt-2 float-end">
    <span id="totalCount1"></span>
    <svg onclick="showEntityModel()" xmlns="http://www.w3.org/2000/svg" width="30" height="30" id="property" data-bs-placement="bottom" data-bs-title="Column Chooser" fill="currentColor" style="cursor:pointer" class="bi bi-database float-end cls-section-icons" viewBox="0 0 16 16"> <path d="M4.318 2.687C5.234 2.271 6.536 2 8 2s2.766.27 3.682.687C12.644 3.125 13 3.627 13 4c0 .374-.356.875-1.318 1.313C10.766 5.729 9.464 6 8 6s-2.766-.27-3.682-.687C3.356 4.875 3 4.373 3 4c0-.374.356-.875 1.318-1.313ZM13 5.698V7c0 .374-.356.875-1.318 1.313C10.766 8.729 9.464 9 8 9s-2.766-.27-3.682-.687C3.356 7.875 3 7.373 3 7V5.698c.271.202.58.378.904.525C4.978 6.711 6.427 7 8 7s3.022-.289 4.096-.777A4.92 4.92 0 0 0 13 5.698ZM14 4c0-1.007-.875-1.755-1.904-2.223C11.022 1.289 9.573 1 8 1s-3.022.289-4.096.777C2.875 2.245 2 2.993 2 4v9c0 1.007.875 1.755 1.904 2.223C4.978 15.71 6.427 16 8 16s3.022-.289 4.096-.777C13.125 14.755 14 14.007 14 13V4Zm-1 4.698V10c0 .374-.356.875-1.318 1.313C10.766 11.729 9.464 12 8 12s-2.766-.27-3.682-.687C3.356 10.875 3 10.373 3 10V8.698c.271.202.58.378.904.525C4.978 9.71 6.427 10 8 10s3.022-.289 4.096-.777A4.92 4.92 0 0 0 13 8.698Zm0 3V13c0 .374-.356.875-1.318 1.313C10.766 14.729 9.464 15 8 15s-2.766-.27-3.682-.687C3.356 13.875 3 13.373 3 13v-1.302c.271.202.58.378.904.525C4.978 12.71 6.427 13 8 13s3.022-.289 4.096-.777c.324-.147.633-.323.904-.525Z" /></svg>
    <div class="float-end" id="divimport" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="Import">
        <svg xmlns="http://www.w3.org/2000/svg" data-bs-placement="bottom" id="import" data-bs-title="Import" width="30" height="30" fill="currentColor" style="cursor:pointer" class="bi bi-box-arrow-in-down float-end cls-section-icons" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M3.5 6a.5.5 0 0 0-.5.5v8a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5v-8a.5.5 0 0 0-.5-.5h-2a.5.5 0 0 1 0-1h2A1.5 1.5 0 0 1 14 6.5v8a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 14.5v-8A1.5 1.5 0 0 1 3.5 5h2a.5.5 0 0 1 0 1h-2z"></path>
            <path fill-rule="evenodd" d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"></path>
        </svg>
    </div>
    <svg xmlns="http://www.w3.org/2000/svg" data-bs-placement="bottom" id="export" data-bs-title="Export" onclick="exportData()" width="30" height="30" fill="currentColor" style="cursor:pointer;padding-top:1px;padding-bottom:0px !important" class="bi bi-box-arrow-in-up float-end cls-section-icons" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M3.5 10a.5.5 0 0 1-.5-.5v-8a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 .5.5v8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 0 0 1h2A1.5 1.5 0 0 0 14 9.5v-8A1.5 1.5 0 0 0 12.5 0h-9A1.5 1.5 0 0 0 2 1.5v8A1.5 1.5 0 0 0 3.5 11h2a.5.5 0 0 0 0-1h-2z" />
        <path fill-rule="evenodd" d="M7.646 4.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 5.707V14.5a.5.5 0 0 1-1 0V5.707L5.354 7.854a.5.5 0 1 1-.708-.708l3-3z" />
    </svg>

    <svg xmlns="http://www.w3.org/2000/svg" data-bs-placement="bottom" id="exportDateRange" data-bs-title="Export Date Range" onclick="exportDateRangeData()" width="30" height="30" fill="currentColor" style="cursor:pointer;padding-top:1px;padding-bottom:0px !important" class="bi bi-box-arrow-in-up float-end cls-section-icons" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M3.5 10a.5.5 0 0 1-.5-.5v-8a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 .5.5v8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 0 0 1h2A1.5 1.5 0 0 0 14 9.5v-8A1.5 1.5 0 0 0 12.5 0h-9A1.5 1.5 0 0 0 2 1.5v8A1.5 1.5 0 0 0 3.5 11h2a.5.5 0 0 0 0-1h-2z" />
        <path fill-rule="evenodd" d="M7.646 4.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 5.707V14.5a.5.5 0 0 1-1 0V5.707L5.354 7.854a.5.5 0 1 1-.708-.708l3-3z" />
    </svg>
    <div class="float-end" id="divimpDateRange" data-bs-toggle="tooltip" data-bs-placement="bottom" data-bs-title="Import Date Range">
        <svg xmlns="http://www.w3.org/2000/svg" data-bs-placement="bottom" id="importDateRange" data-bs-title="Import Date Range" width="30" height="30" fill="currentColor" style="cursor:pointer" class="bi bi-box-arrow-in-down float-end cls-section-icons" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M3.5 6a.5.5 0 0 0-.5.5v8a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5v-8a.5.5 0 0 0-.5-.5h-2a.5.5 0 0 1 0-1h2A1.5 1.5 0 0 1 14 6.5v8a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 14.5v-8A1.5 1.5 0 0 1 3.5 5h2a.5.5 0 0 1 0 1h-2z"></path>
            <path fill-rule="evenodd" d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"></path>
        </svg>
    </div>
</div>

<div hidden>
    <div id="sampleFileImport">
        <p>
            <b>Download sample file: </b>
            <a href="#" onclick="sampleFileImportDownload()" class="aTagColor">Click here</a>
        </p>
        <p>
            <b>Import file: </b>
            <a href="#" onclick="importData()" class="aTagColor">Click here</a>
        </p>
    </div>
</div>

<div hidden>
    <div id="sampleFileDateRangeImport">
        <p>
            <b>Download sample file: </b>
            <a href="#" onclick="sampleFileDateRangeImportDownload()" class="aTagColor">Click here</a>
        </p>
        <p>
            <b>Import file: </b>
            <a href="#" onclick="importDateRangeData()" class="aTagColor">Click here</a>
        </p>
    </div>
</div>

InventoryTracker-WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/Css/Style.css">
</head>
<body>
    @Html.Partial("_Loader")
    <nav class="navbar navbar-expand-lg  fixed-top navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand ms-5" href="#">Inventory Tracker</a>
            <div class="text-white">Instance: <a href="@Url.Action("Index","MultiInstance")" title="Click to change instance">@HttpContext.Current.Session["instance_name"]</a></div>
            <div class="d-flex">
                <div id="selectedMenu" class="mt-2" style="color:wheat"></div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse dropend navbar-collapse me-5" id="navbarNavDarkDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                @*Home*@
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark" id="menuList">
                                <li><a class="dropdown-item" href="@Url.Action("Index","Entity")" id="menuEntTemp">Entity templates</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("Index","Equipment")" id="menuEquipTemp">Equipment templates</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("EntitySearch","Entity")" id="menuEntSearch">Entity search</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("EquipmentSearch","Equipment")" id="menuEquipSearch">Equipment search</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("EquipmentEntityAssignment","Equipment")" id="menuEntEquAss">Equipment-Entity Assignment</a></li>
                                <li><a class="dropdown-item" id="menuEquEntAss" href="@Url.Action("EntityEquipmentAssignment","Entity")">Entity-Equipment Assignment</a></li>
                                <li><a class="dropdown-item" id="menuUserMaster" href="@Url.Action("Index","UserMaster")">User Master</a></li>
                                <li><a class="dropdown-item" id="menuUserDefinition" href="@Url.Action("Index","UserDefinition")">User Definition</a></li>
                                <li><a class="dropdown-item" id="menuMap" href="@Url.Action("Index","Map")">Map</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="d-flex">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavSelectedProfAction" aria-controls="navbarNavSelectedProfAction" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse dropstart navbar-collapse" id="navbarNavSelectedProfAction">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="textMenu" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Profile
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark" id="profMenuList">
                                <li><a class="dropdown-item" href="@Url.Action("Index","ResetPassword")" id="resetPass">Reset Password</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("Signout","Login")" id="signOut">Sign out</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>


    <div class="body-content mt-3">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

InventoryTracker-WebApp/Views/Shared/_Loader.cshtml
<div class="overlay d-none" style="z-index:999999">
    <div class="d-flex justify-content-center">
        <div class="spinner-border text-danger position-fixed loader" role="status">
        </div>
    </div>
</div>